Add files via upload
EBOGDAO/ParticipationAgreement pull request #1
Opened 2021-07-10 21:24 UTC by stinkyfi

Adding the Participation Agreement smart contrats.

2021-07-10 22:10 UTC, mehtaculous commented on contracts/EBOGAgreement_ChangeMind.sol
> +            if(optOut[msg.sender]){
You can change these nested `if` statements to:
```
if (optIn[msg.sender]) {
    return "This address voted to Opt In";
} else if (optOut[msg.sender]) {
    return "This address voted to Opt Out";
} else {
    return "This address has not voted.";
}
```

2021-07-10 22:13 UTC, mehtaculous commented on contracts/EBOGAgreement_SingleVote.sol
> +            if(optOut[_address]){
See comment above

2021-07-10 22:13 UTC, mehtaculous commented on contracts/EBOGAgreement_ChangeMind.sol
> +            if(optOut[_address]){
See comment below

2021-07-10 22:14 UTC, mehtaculous commented on contracts/EBOGAgreement_SingleVote.sol
> +    mapping (address => uint256) voteChanges;
This doesn't seem necessary if addresses can only vote once

2021-07-10 22:15 UTC, mehtaculous commented on contracts/EBOGAgreement_SingleVote.sol
> +        optOut[msg.sender] = false;
default boolean value will always be false so it is not necessary to set this value as false

2021-07-10 22:15 UTC, mehtaculous commented on contracts/EBOGAgreement_SingleVote.sol
> +        optIn[msg.sender]  = false;
default boolean value will always be false so it is not necessary to set this value as false

2021-07-10 22:18 UTC, mehtaculous commented on contracts/EBOGAgreement_SingleVote.sol
> +        voteChanges[msg.sender] += 1;
this can be removed

2021-07-10 22:18 UTC, mehtaculous commented on contracts/EBOGAgreement_SingleVote.sol
> +        voteChanges[msg.sender] += 1;
this can be removed

2021-07-10 22:21 UTC, mehtaculous commented on contracts/EBOGAgreement_SingleVote.sol
> +        require(!optOut[msg.sender], 'You have already voted: Opted Out');
Since users can check their vote status, it doesn't seem necessary to let the user know which option they voted for. I would change this to a one-liner:
```
require(!optIn[msg.sender] || !optOut[msg.sender], 'You have already voted');
```

2021-07-10 22:23 UTC, mehtaculous commented on contracts/EBOGAgreement_ChangeMind.sol
> +        optIn[msg.sender]  = true;
I would assume we don't want just anyone to call this function, might need a requirement that verifies the address is whitelisted...

2021-07-10 22:23 UTC, stinkyfi commented on contracts/EBOGAgreement_ChangeMind.sol
> +            if(optOut[msg.sender]){
Changes have been made

2021-07-10 22:23 UTC, stinkyfi commented on contracts/EBOGAgreement_SingleVote.sol
> +            if(optOut[_address]){
Changes have been made

2021-07-10 22:23 UTC, stinkyfi commented on contracts/EBOGAgreement_ChangeMind.sol
> +            if(optOut[_address]){
Changes have been made

2021-07-10 22:23 UTC, mehtaculous requested changes
A few suggestions for code refactoring

2021-07-10 22:24 UTC, stinkyfi commented on contracts/EBOGAgreement_SingleVote.sol
> +    mapping (address => uint256) voteChanges;
Left over code from the ChangeMind contract. Thanks, has been cleaned up

2021-07-10 22:24 UTC, stinkyfi commented on contracts/EBOGAgreement_SingleVote.sol
> +        optOut[msg.sender] = false;
More copied code from ChangeMind. Has been cleaned up

2021-07-10 22:24 UTC, stinkyfi commented on contracts/EBOGAgreement_SingleVote.sol
> +        optIn[msg.sender]  = false;
Copy Pasta is bad

2021-07-10 22:32 UTC, stinkyfi commented on contracts/EBOGAgreement_SingleVote.sol
> +        require(!optOut[msg.sender], 'You have already voted: Opted Out');
I wasn't thinking about this from the front end perspective. Getting the address status onload and preventing the button from being clicked. I will make the proposed changes

2021-07-12 00:46 UTC, stinkyfi commented on contracts/EBOGAgreement_ChangeMind.sol
> +        optIn[msg.sender]  = true;
I now have a working version that uses OZ(Ownable and AccessControl). I modified HQ20's Whitelist contract to also have an `addMembers()` function so we can pass it an array with all 775 addresses. Only the contract owner will have control to add more members. Only members can vote to opt-in and opt-out. All other addresses get rejected.

2021-07-12 21:11 UTC, merged